### PR TITLE
Internal Path and loader for Lua

### PR DESCRIPTION
**Pull request by Sicprofundus**
- removed "2" from "openfolderMQ2" for launcher
- added lua to the open folder menu in the launcher
- added  Lua to internal paths

### CODE REVIEW

**Comment by Knightly1** [comment]
This would be wrong for anyone who changes their lua path.

**Comment by Sicprofundus** [comment]
> This would be wrong for anyone who changes their lua path. It's launching from the relative directory of the launcher and the path is never updated.

how do we correct that? Did a miss a part about how this already works for other folders?

**Comment by brainiac** [comment]
Lua path is configurable in the lua plugin. It isn't like the other dirs.
https://github.com/macroquest/macroquest/blob/master/src/plugins/lua/MQ2Lua.cpp#L743-L765

**Comment by Sicprofundus** [comment]
is the itent of "click the button to open your directory" still viable?

is this workable or should i close it?

**Comment by Knightly1** [comment]
What brainiac said.  It's also not really relevant outside the context of the plugin, so the plugin provides the TLO for the path here: https://github.com/macroquest/macroquest/blob/master/src/plugins/lua/MQ2Lua.cpp#L345-L350

So you'd not have those paths in core.  To add them to the launcher, you'd probably want to export something from the plugin you can use to get the path.  Whether that is moving the config get to a shared header or actually exporting functionality I'd have to look at.

**Comment by Sicprofundus** [comment]
closing MR

**Pull request closed without merging**
